import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(__dirname, "sample-upload.pdf");

/**
 * Generate a valid PDF using pdfkit.
 * This runs as a pretest hook and can also be invoked standalone:
 *   node test-data/generate-sample.js
 */
async function main() {
  // Dynamic import so this works with ESM
  const require = createRequire(import.meta.url);
  const PDFDocument = require("pdfkit");

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER" });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", async () => {
      const pdfBuffer = Buffer.concat(chunks);
      await fs.promises.writeFile(outPath, pdfBuffer);
      console.log(`✔ Wrote ${outPath} (${pdfBuffer.length} bytes)`);
      resolve();
    });
    doc.on("error", reject);

    doc.fontSize(20).text("Automation Anywhere — Sample Upload PDF", 50, 50);
    doc
      .moveDown()
      .fontSize(12)
      .text(
        "Generated by test-data/generate-sample.js for Playwright UC2 form-upload test.",
        50,
        80
      );
    doc
      .moveDown()
      .fontSize(10)
      .text(`Generated at: ${new Date().toISOString()}`, 50, 110);

    doc.end();
  });
}

await main();
